version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: "Use Python v3.6.5"
          command: |
            pyenv versions
            pyenv global 3.6.5
      - run:
          name: "Build"
          command: |
            make test_unit
            make regress_prepare
            make regress_run
            make regress_report
          environment:
            DOCKER_COMPOSE_VERSION: 1.25.5
            REGRESSION_PY_VER: 3.6.5
            VENV_PYTHON_VERSION: python3.6
